
import { Inter } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import "./globals.css"
import theme from "./theme";


export const metadata = {
  title: "Social Network",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider theme={theme}> 
            {children}
        </ChakraProvider>
      </body>
    </html>
  );
}