CREATE TABLE IF NOT EXISTS AddMemberRequests (
    RequestID INTEGER PRIMARY KEY AUTOINCREMENT,
    GroupID INTEGER,
    RequesterID INTEGER,
    RequestedID INTEGER,
    Status INTEGER,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GroupID) REFERENCES Groups(Id),
    FOREIGN KEY (RequesterID) REFERENCES User(Id),
    FOREIGN KEY (RequestedID) REFERENCES User(Id)
)