CREATE TABLE IF NOT EXISTS EventVisibility(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    EventID INTERGER,
    UserId INTERGER,
    FOREIGN KEY(EventID) REFERENCES Event(ID),
    FOREIGN KEY(UserId) REFERENCES User(Id)
);